package lootic.game.controllers;

public enum InputState {
	DASH_LEFT, DASH_RIGHT, ATTACK_NEUTRAL, SHEILD, ROLL_LEFT, ROLL_RIGHT, COUNTER,
	ATTACK_UP, ATTACK_LEFT, ATTACK_RIGHT, ATTACK_DOWN, ATTACK_CHARGE, JUMP;
}